supported = [
    ('text/plain', 'Text'),

    ('heading', 'Popular Languages'),

    ('text/x-python', 'Python'),
    ('application/x-ruby', 'Ruby'),
    ('text/x-gosrc', 'Go'),
    ('text/x-swift', 'Swift'),
    ('text/x-csrc', 'C'),
    ('text/x-csharp', 'C#'),
    ('text/x-c++src', 'C++'),
    ('text/x-java', 'Java'),
    ('text/html', 'HTML'),
    ('text/css', 'CSS'),
    ('application/javascript', 'JavaScript'),
    ('application/json', 'JSON'),
    ('text/x-markdown', 'Markdown'),

    ('heading', 'Programming Languages'),

    ('application/x-actinoscript', 'ActionScript'),
    ('application/x-actionscript3', 'ActionScript3'),
    ('text/x-ada', 'Ada'),
    ('text/x-arduino', 'Arduino'),
    ('text/x-boo', 'Boo'),
    ('text/x-csrc', 'C'),
    ('text/x-csharp', 'C#'),
    ('text/x-c++src', 'C++'),
    ('text/coffeescript', 'CoffeeScript'),
    ('text/x-crystal', 'Crystal'),
    ('text/x-dsrc', 'D'),
    ('text/x-dart', 'Dart'),
    ('text/x-pascal', 'Delphi'),
    ('text/x-erlang', 'Erlang'),
    ('text/x-fortran', 'Fortran'),
    ('text/x-glslsrc', 'GLSL'),
    ('text/x-gosrc', 'Go'),
    ('text/x-haskell', 'Haskell'),
    ('text/x-java', 'Java'),
    ('application/javascript', 'JavaScript'),
    ('text/x-julia', 'Julia'),
    ('text/x-common-lisp', 'Lisp'),
    ('text/x-lua', 'Lua'),
    ('text/matlab', 'Matlab'),
    ('text/x-ocaml', 'OCaml'),
    ('text/x-objective-c', 'Objective-C'),
    ('application/x-php', 'PHP'),
    ('text/x-prolog', 'Prolog'),
    ('text/x-python', 'Python'),
    ('text/basic', 'QBasic'),
    ('application/x-ruby', 'Ruby'),
    ('text/rust', 'Rust'),
    ('text/x-scala', 'Scala'),
    ('text/x-scheme', 'Scheme'),
    ('text/x-swift', 'Swift'),
    ('text/x-typescript', 'TypeScript'),
    ('text/x-vala', 'Vala'),
    ('text/x-vbnet', 'Visual Basic.NET'),

    ('heading', 'Low-Level Languages'),

    ('text/x-gas', 'ASM'),
    ('x-text/hexdump', 'Hexdump'),
    ('text/x-llvm', 'LLVM'),
    ('text/x-nasm', 'NASM'),
    ('text/x-nasm-objdump', 'NASM Objdump'),
    ('text/x-vhdl', 'VHDL'),
    ('text/x-verilog', 'Verilog'),

    ('heading', 'Markup Languages'),

    ('text/x-bbcode', 'BBCode'),
    ('text/css', 'CSS'),
    ('text/x-gnuplot', 'Gnuplot'),
    ('text/html', 'HTML'),
    ('application/json', 'JSON'),
    ('text/x-less-css', 'Less'),
    ('text/x-markdown', 'Markdown'),
    ('application/postscript', 'Postscript'),
    ('application/x-qml', 'QML'),
    ('text/x-rst', 'reStructuredText'),
    ('text/x-sass', 'Sass'),
    ('text/x-scss', 'SCSS'),
    ('text/x-tex', 'TeX'),
    ('application/x-troff', 'Troff'),
    ('text/x-trac-wiki', 'Wiki'),
    ('text/xml', 'XML'),
    ('text/x-yaml', 'YAML'),

    ('heading', 'Templating Languages'),

    ('x-text/html+ng2', 'Angular'),
    ('text/html+django', 'Django'),
    ('application/x-ruby-templating', 'ERB'),
    ('text/html+handlebars', 'Handlebars'),

    ('heading', 'Shell Languages'),

    ('application/x-awk', 'Awk'),
    ('application/x-fish', 'Fish'),
    ('text/x-powershell', 'PowerShell'),
    ('application/x-sh', 'Bash'),
    ('application/x-sh', 'tcsh'),

    ('heading', 'Configuration Languages'),

    ('text/x-apacheconf', 'Apache'),
    ('text/x-dockerfile-config', 'Docker'),
    ('text/x-ini', 'INI'),
    ('text/x-kconfig', 'Kconfig'),
    ('text/x-nginx-conf', 'Nginx'),
    ('x-text/pkgconfig', 'pkg-config'),
    ('text/x-java-properties', 'Properties'),
    ('text/x-windows-registry', 'Registry'),
    ('text/x-vim', 'Vim'),

    ('heading', 'Automation Languages'),

    ('x-text/applescript', 'AppleScript'),
    ('text/x-autohotkey', 'AutoHotkey'),
    ('text/x-autoit', 'AutoIt'),

    ('heading', 'Code Building Languages'),

    ('text/x-cmake', 'CMake'),
    ('text/x-makefile', 'Makefile'),

    ('heading', 'Packaging Languages'),

    ('x-text/debcontrol', 'Debian Control'),
    ('text/x-nix', 'Nix'),
    ('text/x-nsis', 'NSIS'),
    ('text/x-rpm-spec', 'RPMSpec'),

    ('heading', 'Specification Languages'),

    ('text/x-bnf', 'BNF'),
    ('application/xml-dtd', 'DTD'),
    ('text/x-ebnf', 'EBNF'),
    ('x-text/protobuf', 'ProtoBuf'),
    ('x-text/puppet', 'Puppet'),

    ('heading', 'Esoteric Languages'),

    ('application/x-befunge', 'Befunge'),
    ('application/x-brainfuck', 'BrainFuck'),

    ('heading', 'Other Languages'),

    ('text/x-bibtex', 'BibTeX'),
    ('x-text/bro', 'BRO'),
    ('text/x-cobol', 'COBOL'),
    ('text/x-cuda', 'CUDA'),
    ('text/x-diff', 'Diff'),
    ('application/x-forth', 'Forth'),
    ('text/x-irclog', 'IRC'),
    ('application/mathematica', 'Mathematica'),
    ('text/x-mysql', 'MySQL'),
    ('text/x-postgresql', 'PostgreSQL'),
    ('text/swig', 'SWIG'),
]

types = {entry[0]: entry[1] for entry in supported if entry[0] != 'heading'}

languages = '\n'.join('<option value={}>{}</option>'.format(entry[0], entry[1]) if entry[0] != 'heading' else '<option disabled>──────────</option>\n<option disabled>{}</option>'.format(entry[1]) for entry in supported)
